permalink: /:year/:month/:title/
url: http://xuzhen1994.github.io
author: xuzhen
timezone: Asia/Beijing
paginate: 20
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]